# Generated by Django 3.0.8 on 2021-06-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20200705_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='first_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='last_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
